### ISSUE TITLE
New Spawn & Entity System

### ISSUE THREAD

**Issue by starlight-caffeine** [SpaceWAGdev/Bongocat#4]
The new spawn system should include:
- The possibility of more than 2 types of spawned types
- A better algorithm
The new entity system should include:
- Faster performance ( preferably w/o every instantiated object having an Update Loop )
- No more per-entity movement, but a centralized movement control system

**Comment by SpaceWAGdev** [comment]
> The new spawn system should include:

>     * The possibility of more than 2 types of spawned types
- implemented
>     * A better algorithm
- implemented
>       The new entity system should include:
>     * Faster performance ( preferably w/o every instantiated object having an Update Loop )
- implemented (~500fps in editor on windows 10 laptop)
>     * No more per-entity movement, but a centralized movement control system
- implemented
